In [2]:
import pandas as pd


# 매매
# 아파트, 오피스텔, 단독다가구, 연립 다세대 파일 열기
apt = pd.read_excel('C:/Users/user/Desktop/데이터들/Data/아파트_매매_33역.xlsx')
op = pd.read_excel('C:/Users/user/Desktop/데이터들/Data/오피스텔_매매_33역.xlsx')
dan = pd.read_excel('C:/Users/user/Desktop/데이터들/Data/단독다가구_매매_33역.xlsx')
yun = pd.read_excel('C:/Users/user/Desktop/데이터들/Data/연립다세대_매매_33역.xlsx')

# 전,월세
jeon = pd.read_excel('C:/Users/user/Desktop/데이터들/Data/전세_2호선_33역_통일.xlsx')
wol = pd.read_excel('C:/Users/user/Desktop/데이터들/Data/월세_2호선_33역_통일.xlsx')

In [3]:
# 데이터 통합 준비

# 거래유형 추가
apt['거래유형'] = '매매'
op['거래유형'] = '매매'
dan['거래유형'] = '매매'
yun['거래유형'] = '매매'

for df in [apt, op, dan, yun]:
    df['보증금'] = pd.NA
    df['임대료'] = pd.NA

apt.head(5)

   역명  계약연월   거래금액 주택유형 거래유형   보증금   임대료
0  시청  2025  27000  아파트   매매  <NA>  <NA>
1  시청  2025  27000  아파트   매매  <NA>  <NA>
2  시청  2025  27000  아파트   매매  <NA>  <NA>
3  시청  2024  55000  아파트   매매  <NA>  <NA>
4  시청  2024  55000  아파트   매매  <NA>  <NA>

In [21]:
dan.head()

   역명  계약연월    거래금액 주택유형 거래유형   보증금   임대료
0  신당  2025  160000  다가구   매매  <NA>  <NA>
1  신당  2025   60000   단독   매매  <NA>  <NA>
2  신당  2025  164000   단독   매매  <NA>  <NA>
3  신당  2025  118000   단독   매매  <NA>  <NA>
4  신당  2022  131800  다가구   매매  <NA>  <NA>

In [6]:
# 전, 월세 거래유형 생성
jeon['거래유형'] = '전세'
wol['거래유형'] = '월세'

jeon['거래금액'] = pd.NA
wol['거래금액'] = pd.NA

In [17]:
jeon.rename(columns={'전세보증금': '보증금'}, inplace= True)

jeon.head(10)

   역명  계약연월    보증금 주택유형 거래유형  거래금액
0  시청  2022  21800  아파트   전세  <NA>
1  시청  2022  31000  아파트   전세  <NA>
2  시청  2022  20800  아파트   전세  <NA>
3  시청  2022  22000  아파트   전세  <NA>
4  시청  2022  27000  아파트   전세  <NA>
5  시청  2022   9698  아파트   전세  <NA>
6  시청  2022  51000  아파트   전세  <NA>
7  시청  2022  25000  아파트   전세  <NA>
8  시청  2022  36000  아파트   전세  <NA>
9  시청  2022  23000  아파트   전세  <NA>

In [8]:
wol.head(5)

   역명  계약연월    보증금  임대료 주택유형 거래유형  거래금액
0  시청  2025   2000  160  아파트   월세  <NA>
1  시청  2023  10000   50  아파트   월세  <NA>
2  시청  2023  26250   45  아파트   월세  <NA>
3  시청  2023  10000   50  아파트   월세  <NA>
4  시청  2023   2000  110  아파트   월세  <NA>

In [20]:
wol['주택유형'].unique()

<StringArray>
['아파트', '단독다가구', '연립다세대', '오피스텔']
Length: 4, dtype: str

In [18]:
real_estate = pd.concat(
    [
        apt,
        op,
        dan,
        yun,
        jeon,
        wol
    ],
    ignore_index=True
)

In [19]:
print(real_estate.head())
print(real_estate.shape)

print(real_estate['주택유형'].unique())
print(real_estate['거래유형'].unique())

   역명  계약연월   거래금액 주택유형 거래유형   보증금   임대료
0  시청  2025  27000  아파트   매매  <NA>  <NA>
1  시청  2025  27000  아파트   매매  <NA>  <NA>
2  시청  2025  27000  아파트   매매  <NA>  <NA>
3  시청  2024  55000  아파트   매매  <NA>  <NA>
4  시청  2024  55000  아파트   매매  <NA>  <NA>
(802751, 7)
<StringArray>
['아파트', '오피스텔', '다가구', '단독', '연립', '다세대', '연립다세대', '단독다가구']
Length: 8, dtype: str
<StringArray>
['매매', '전세', '월세']
Length: 3, dtype: str

In [22]:
# 주택 유형이 아파트 오피스텔 단독다가구 연립다세대로만 나와야 하는데 단독, 연립, 다가구, 다세대가 각각 따로 있음 -> 하나로 합치기
dan['주택유형'] = (
    dan['주택유형']
    .astype(str)
    .str.strip()
    .replace({
        '단독': '단독다가구',
        '다가구': '단독다가구'
    })
)

yun['주택유형'] = (
    yun['주택유형']
    .astype(str)
    .str.strip()
    .replace({
        '연립': '연립다세대',
        '다세대': '연립다세대'
    })
)

In [23]:
print('단독다가구:', dan['주택유형'].unique())
print('연립다세대:', yun['주택유형'].unique())

단독다가구: <StringArray>
['단독다가구']
Length: 1, dtype: str
연립다세대: <StringArray>
['연립다세대']
Length: 1, dtype: str

In [24]:
real_estate1 = pd.concat(
    [
        apt,
        op,
        dan,
        yun,
        jeon,
        wol
    ],
    ignore_index=True
)

In [25]:
print(real_estate1.head())
print(real_estate1.shape)

print(real_estate1['주택유형'].unique())
print(real_estate1['거래유형'].unique())

   역명  계약연월   거래금액 주택유형 거래유형   보증금   임대료
0  시청  2025  27000  아파트   매매  <NA>  <NA>
1  시청  2025  27000  아파트   매매  <NA>  <NA>
2  시청  2025  27000  아파트   매매  <NA>  <NA>
3  시청  2024  55000  아파트   매매  <NA>  <NA>
4  시청  2024  55000  아파트   매매  <NA>  <NA>
(802751, 7)
<StringArray>
['아파트', '오피스텔', '단독다가구', '연립다세대']
Length: 4, dtype: str
<StringArray>
['매매', '전세', '월세']
Length: 3, dtype: str

In [27]:
real_estate1.to_csv(
    'C:/Users/user/Desktop/데이터들/Data/부동산통합.csv',
    index=False,
    encoding='utf-8-sig'
)

In [1]:
import pandas as pd

test = pd.read_csv('C:/Users/user/Desktop/데이터들/Data/부동산통합.csv', encoding = 'utf-8-sig',index_col=False)
test.head()

   역명  계약연월     거래금액 주택유형 거래유형  보증금  임대료
0  시청  2025  27000.0  아파트   매매  NaN  NaN
1  시청  2025  27000.0  아파트   매매  NaN  NaN
2  시청  2025  27000.0  아파트   매매  NaN  NaN
3  시청  2024  55000.0  아파트   매매  NaN  NaN
4  시청  2024  55000.0  아파트   매매  NaN  NaN

In [2]:
type(test['거래금액'])

pandas.Series