In [1]:
import pandas as pd

subway = pd.read_csv('C:/Users/user/Desktop/데이터들/Data/subway_통합.csv',encoding='utf-8-sig',index_col=False)
subway.head()

     연도  노선명       역명  승차총승객수  하차총승객수   총이용량
0  2022  2호선  구로디지털단지   18363   18352  36715
1  2022  2호선      신대방   11652   11727  23379
2  2022  2호선       신림   29564   29162  58726
3  2022  2호선       봉천    9207    8941  18148
4  2022  2호선       사당   15292   16173  31465

In [2]:
real_estate = pd.read_csv('C:/Users/user/Desktop/데이터들/Data/부동산통합.csv',encoding='utf-8-sig',index_col=False)
real_estate.head()

   역명  계약연월     거래금액 주택유형 거래유형  보증금  임대료
0  시청  2025  27000.0  아파트   매매  NaN  NaN
1  시청  2025  27000.0  아파트   매매  NaN  NaN
2  시청  2025  27000.0  아파트   매매  NaN  NaN
3  시청  2024  55000.0  아파트   매매  NaN  NaN
4  시청  2024  55000.0  아파트   매매  NaN  NaN

In [3]:
# 둘 컬럼명 맞추기

# subway의 노선명 -> 역명
# subway = subway.rename(columns={'노선명' : '역명'})
# real_estate의 계약연월 -> 연도
real_estate = real_estate.rename(columns={'계약연월' : '연도'})

print(subway.head(5))
print(real_estate.head(5))

     연도  노선명       역명  승차총승객수  하차총승객수   총이용량
0  2022  2호선  구로디지털단지   18363   18352  36715
1  2022  2호선      신대방   11652   11727  23379
2  2022  2호선       신림   29564   29162  58726
3  2022  2호선       봉천    9207    8941  18148
4  2022  2호선       사당   15292   16173  31465
   역명    연도     거래금액 주택유형 거래유형  보증금  임대료
0  시청  2025  27000.0  아파트   매매  NaN  NaN
1  시청  2025  27000.0  아파트   매매  NaN  NaN
2  시청  2025  27000.0  아파트   매매  NaN  NaN
3  시청  2024  55000.0  아파트   매매  NaN  NaN
4  시청  2024  55000.0  아파트   매매  NaN  NaN

In [4]:
subway.columns

Index(['연도', '노선명', '역명', '승차총승객수', '하차총승객수', '총이용량'], dtype='str')

In [9]:
subway = subway.drop(columns=['노선명'])
print(subway.columns)

Index(['연도', '역명', '승차총승객수', '하차총승객수', '총이용량'], dtype='str')

In [10]:
print(real_estate.columns)

Index(['역명', '연도', '거래금액', '주택유형', '거래유형', '보증금', '임대료'], dtype='str')

In [11]:
real_estate.to_csv(
    'C:/Users/user/Desktop/데이터들/Data/부동산_통합_최종.csv',
    index=False,
    encoding='utf-8-sig'
)

In [12]:
subway.to_csv(
    'C:/Users/user/Desktop/데이터들/Data/지하철_통합_최종.csv',
    index=False,
    encoding='utf-8-sig'
)

In [15]:
subway.to_csv(
    'C:/Users/user/Desktop/데이터들/Data/지하철_통합_최종최종.csv',
    index=False,
    encoding='utf-8'
)

In [14]:
with open('C:/Users/user/Desktop/데이터들/Data/지하철_통합_최종.csv', 'r', encoding='utf-8-sig') as f:
    print(f.readline())

연도,역명,승차총승객수,하차총승객수,총이용량

In [16]:
with open(
    'C:/Users/user/Desktop/데이터들/Data/지하철_통합_최종최종.csv',
    'r',
    encoding='utf-8'
) as f:
    print(f.readline())

연도,역명,승차총승객수,하차총승객수,총이용량

In [5]:
merged = pd.merge(
    real_estate,
    subway,
    on=['연도', '역명'],
    how='inner'
)

merged.head()

   역명    연도     거래금액 주택유형 거래유형  보증금  임대료  노선명  승차총승객수  하차총승객수   총이용량
0  시청  2025  27000.0  아파트   매매  NaN  NaN  2호선    8910    6937  15847
1  시청  2025  27000.0  아파트   매매  NaN  NaN  2호선   29518   28534  58052
2  시청  2025  27000.0  아파트   매매  NaN  NaN  2호선   30853   28888  59741
3  시청  2025  27000.0  아파트   매매  NaN  NaN  2호선   16584   13358  29942
4  시청  2025  27000.0  아파트   매매  NaN  NaN  2호선    8004    6253  14257

In [7]:
merged.to_csv(
    'C:/Users/user/Desktop/데이터들/Data/subway_realestate_merged.csv',
    index=False,
    encoding='utf-8-sig'
)