In [1]:
import pandas as pd

subway = pd.read_csv('C:/Users/user/Desktop/데이터들/Data/subway_2호선_통합(역제거).csv',encoding='utf-8-sig',index_col=False)
subway.head()

     연도  노선명       역명  승차총승객수  하차총승객수
0  2022  2호선  구로디지털단지   18363   18352
1  2022  2호선      신대방   11652   11727
2  2022  2호선       신림   29564   29162
3  2022  2호선       봉천    9207    8941
4  2022  2호선       사당   15292   16173

In [2]:
subway['총이용량'] = subway['승차총승객수'] + subway['하차총승객수']
subway.head()

     연도  노선명       역명  승차총승객수  하차총승객수   총이용량
0  2022  2호선  구로디지털단지   18363   18352  36715
1  2022  2호선      신대방   11652   11727  23379
2  2022  2호선       신림   29564   29162  58726
3  2022  2호선       봉천    9207    8941  18148
4  2022  2호선       사당   15292   16173  31465

In [3]:
subway.to_csv(
    'C:/Users/user/Desktop/데이터들/subway/subway_통합.csv',
    index=False,
    encoding='utf-8-sig'
)